<?php
/**
 * insert_file.php — Insertion de fichier / File insertion
 * FR: Enregistre un fichier uploade dans la base de donnees
 * EN: Saves an uploaded file to the database
 */
session_start();
require_once "../Class/DatabaseHandler.php";
require_once "../info_exe/dbCheck.php";

$id_user = $_SESSION["info_index"][1][0]["id_user"] ?? null;
if (!$id_user) {
    http_response_code(403);
    echo "Non autorisé";
    exit;
}

// FR: Recoit le vrai nom de fichier genere par upload_chunk.php
// EN: Receives the real filename generated by upload_chunk.php
$generatedFileName = isset($_POST["generatedFileName"]) ? basename($_POST["generatedFileName"]) : '';
$originalFileName = isset($_POST["insert_file"]) ? $_POST["insert_file"] : '';
$ext = pathinfo($originalFileName, PATHINFO_EXTENSION);

if (empty($generatedFileName)) {
    http_response_code(400);
    echo "Nom de fichier manquant";
    exit;
}
// Connexion à la base
$databaseHandler = new DatabaseHandler($dbname, $username, $password);

// Prépare les données à insérer
$user = [
    'id_projet_img'      => $_POST["file_dowload"],
    'img_projet_src_img' => $generatedFileName,
    'extension_img'      => $ext ? $ext : null, // ajoute l'extension ou null si absente
    'id_user_img'        => $_SESSION["info_index"][1][0]["id_user"]
];

// Insertion sécurisée dans la base
$result = $databaseHandler->insert_safe('projet_img', $user, 'img_projet_src_img');

// Retourne le résultat
if ($result['success']) {
    echo "✅ ".$result['message']." (ID ".$result['id'].") — Fichier : ".$generatedFileName;
} else {
    echo "⚠️ ".$result['message'];
}

// Ferme la connexion
$databaseHandler->closeConnection();
?>
